package cosmo0

import scala.collection.mutable
import scala.collection.mutable.ListBuffer

final case class CppOutput(
    moduleName: String,
    namespace: List[String],
    source: String,
    backendRequirements: List[BackendRequirement] = Nil,
    supportLibraryLinkPlan: SupportLibraryLinkPlan = SupportLibraryLinkPlan.empty,
):
  def runtimeRequirements: List[String] =
    backendRequirements.map(_.legacyName).distinct.sorted

  def supportLibraryLinkArguments: List[String] =
    supportLibraryLinkPlan.linkArguments

object CppBackend:
  def apply(): CppBackend =
    new CppBackend(LirTypeChecker())

final class CppBackend(
    checker: LirTypeChecker,
):
  def emit(module: LirModule): Result[CppOutput] =
    checker.check(module) match
      case checked if checked.isSuccess =>
        val state = State(module)
        val source = state.emit()
        if state.diagnostics.nonEmpty then Result.failure(Phase.Compile, state.diagnostics)
        else
          SupportLibraryLinkPlan.fromBackendRequirements(state.backendRequirements) match
            case Left(diagnostics) =>
              Result.failure(Phase.Compile, diagnostics)
            case Right(linkPlan) =>
              Result.success(
                Phase.Compile,
                CppOutput(module.name, state.namespace, source, state.backendRequirements, linkPlan),
              )
      case failed =>
        Result.failure(
          Phase.Compile,
          failed.diagnostics.map(_.copy(phase = Phase.Compile)),
        )

  private enum EmittedDescriptor:
    case Expr(value: String, requirements: Set[String] = Set.empty)
    case Stmt(value: String, requirements: Set[String] = Set.empty)

  private final case class DeclEnv(
      declarations: List[LirDeclaration],
      byId: Map[LirDeclId, LirDeclaration],
      functions: Map[LirDeclId, LirFunction],
      globals: Map[LirDeclId, LirGlobal],
      typesById: Map[LirDeclId, LirTypeDecl],
      typesByName: Map[String, LirTypeDecl],
      aliasesByName: Map[String, LirTypeAliasDecl],
  )

  private final class State(module: LirModule):
    private val errors = ListBuffer.empty[Diagnostic]
    private val requirements = mutable.LinkedHashSet.empty[BackendRequirement]
    private val env = buildDeclEnv(module)
    private val names = BackendNames(env)

    requirements ++= module.cIncludes.map(include => BackendRequirement.include(include.header))
    requirements ++= module.cppNamespaceImports.flatMap(importValue =>
      importValue.includeHeaders.map(BackendRequirement.include),
    )
    requirements ++= module.cppNamespaceImports.map(importValue =>
      BackendRequirement.cppNamespaceImport(importValue.requirementValue),
    )

    val namespace: List[String] =
      List("cosmo0", safeIdent(module.name, "module"))

    def diagnostics: List[Diagnostic] =
      errors.toList

    def backendRequirements: List[BackendRequirement] =
      requirements.toList.sortBy(_.legacyName)

    def emit(): String =
      val body = ListBuffer.empty[String]
      body += "// Generated by cosmo0 CppBackend."
      body ++= runtimeIncludes
      body += ""
      body += runtimePrelude
      body += ""
      body ++= namespace.map(part => s"namespace $part {")
      body += ""
      body ++= typeForwardDeclarations
      body ++= typeAliasDeclarations
      body ++= functionForwardDeclarations
      body ++= typeDefinitions
      body ++= externFunctionDeclarations
      body ++= globalDefinitions
      body ++= functionDefinitions
      body += ""
      namespace.reverse.foreach(part => body += s"} // namespace $part")
      mainWrapper.foreach { wrapper =>
        body += ""
        body += wrapper
      }
      body.mkString("\n")

    private def buildDeclEnv(module: LirModule): DeclEnv =
      val declarations = module.declarations.sortBy(_.id.value)
      val byId = declarations.foldLeft(Map.empty[LirDeclId, LirDeclaration]) { (acc, declaration) =>
        if acc.contains(declaration.id) then acc else acc.updated(declaration.id, declaration)
      }
      val functions = byId.collect { case (id, function: LirFunction) => id -> function }
      val globals = byId.collect { case (id, global: LirGlobal) => id -> global }
      val typesById = byId.collect { case (id, ty: LirTypeDecl) => id -> ty }
      val typesByName = typesById.values.map(ty => ty.name -> ty).toMap
      val aliasesByName = byId.collect { case (_, alias: LirTypeAliasDecl) => alias.name -> alias }
      DeclEnv(declarations, byId, functions, globals, typesById, typesByName, aliasesByName)

    private def runtimeIncludes: List[String] =
      val base = List(
        "#include <algorithm>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <cstdio>",
        "#include <cstdlib>",
        "#include <fstream>",
        "#include <filesystem>",
        "#include <iterator>",
        "#include <map>",
        "#include <nlohmann/json.hpp>",
        "#include <optional>",
        "#include <set>",
        "#include <sstream>",
        "#include <string>",
        "#include <sys/wait.h>",
        "#include <type_traits>",
        "#include <unordered_map>",
        "#include <utility>",
        "#include <variant>",
        "#include <vector>",
      )
      val fileLevel = module.cIncludes.map(include => s"#include ${include.header}")
      val foreignHeaders = module.cppNamespaceImports.flatMap(importValue =>
        importValue.includeHeaders.map(header => s"#include $header"),
      )
      (base ++ fileLevel ++ foreignHeaders).distinct

    private def runtimePrelude: String =
      """namespace cosmo0_runtime {
        |
        |[[noreturn]] inline void unreachable(const char *reason) {
        |  if (reason == nullptr) {
        |    std::fprintf(stderr, "cosmo0 unreachable\n");
        |  } else {
        |    std::fprintf(stderr, "cosmo0 unreachable: %s\n", reason);
        |  }
        |  std::abort();
        |}
        |
        |[[noreturn]] inline void error_exit(const char *code, const char *message) {
        |  if (message == nullptr) {
        |    std::fprintf(stderr, "cosmo0 error: %s\n", code);
        |  } else {
        |    std::fprintf(stderr, "cosmo0 error: %s: %s\n", code, message);
        |  }
        |  std::abort();
        |}
        |
        |inline void print_value(const std::string &value) {
        |  std::printf("%s", value.c_str());
        |}
        |
        |inline void print_value(const char *value) {
        |  std::printf("%s", value);
        |}
        |
        |inline void print_value(char32_t value) {
        |  std::printf("%u", static_cast<unsigned int>(value));
        |}
        |
        |template <typename T>
        |inline void print_value(const std::optional<T> &value) {
        |  if (value.has_value()) {
        |    std::printf("Some(");
        |    print_value(*value);
        |    std::printf(")");
        |  } else {
        |    std::printf("None");
        |  }
        |}
        |
        |template <typename T>
        |inline void print_value(const T &value) {
        |  if constexpr (std::is_same_v<T, bool>) {
        |    std::printf("%s", value ? "true" : "false");
        |  } else if constexpr (std::is_integral_v<T> && std::is_signed_v<T>) {
        |    std::printf("%lld", static_cast<long long>(value));
        |  } else if constexpr (std::is_integral_v<T> && std::is_unsigned_v<T>) {
        |    std::printf("%llu", static_cast<unsigned long long>(value));
        |  } else if constexpr (std::is_floating_point_v<T>) {
        |    std::printf("%f", static_cast<double>(value));
        |  } else if constexpr (std::is_pointer_v<T>) {
        |    std::printf("%p", static_cast<const void *>(value));
        |  } else {
        |    std::printf("<value>");
        |  }
        |}
        |
        |template <typename T>
        |inline void print(const T &value) {
        |  print_value(value);
        |}
        |
        |template <typename T>
        |inline void println(const T &value) {
        |  print_value(value);
        |  std::printf("\n");
        |}
        |
        |inline std::string read_file(const std::string &path) {
        |  std::ifstream input(path);
        |  if (!input) {
        |    error_exit("cosmo0.runtime.read_file", path.c_str());
        |  }
        |  std::ostringstream output;
        |  output << input.rdbuf();
        |  return output.str();
        |}
        |
        |inline std::vector<std::string> read_dir(const std::string &path) {
        |  std::error_code error;
        |  std::vector<std::string> entries;
        |  for (const auto &entry : std::filesystem::directory_iterator(path, error)) {
        |    entries.push_back(entry.path().filename().string());
        |  }
        |  if (error) {
        |    error_exit("cosmo0.runtime.read_dir", path.c_str());
        |  }
        |  std::sort(entries.begin(), entries.end());
        |  return entries;
        |}
        |
        |inline bool path_is_file(const std::string &path) {
        |  std::error_code error;
        |  return std::filesystem::is_regular_file(path, error);
        |}
        |
        |inline bool path_is_dir(const std::string &path) {
        |  std::error_code error;
        |  return std::filesystem::is_directory(path, error);
        |}
        |
        |inline void write_file(const std::string &path, const std::string &content) {
        |  std::ofstream output(path);
        |  if (!output) {
        |    error_exit("cosmo0.runtime.write_file", path.c_str());
        |  }
        |  output << content;
        |}
        |
        |inline std::vector<std::string> argv_strings(int argc, char **argv) {
        |  std::vector<std::string> args;
        |  for (int index = 1; index < argc; ++index) {
        |    if (argv[index] != nullptr) {
        |      args.push_back(std::string(argv[index]));
        |    }
        |  }
        |  return args;
        |}
        |
        |inline std::string shell_quote(const std::string &value) {
        |  std::string quoted = "'";
        |  for (char ch : value) {
        |    if (ch == '\'') {
        |      quoted += "'\\''";
        |    } else {
        |      quoted.push_back(ch);
        |    }
        |  }
        |  quoted += "'";
        |  return quoted;
        |}
        |
        |inline int command_exit_status(int raw_status) {
        |  if (raw_status == -1) {
        |    return 1;
        |  }
        |  if (WIFEXITED(raw_status)) {
        |    return WEXITSTATUS(raw_status);
        |  }
        |  return raw_status;
        |}
        |
        |inline uint8_t *string_data(const std::string &value) {
        |  return const_cast<uint8_t *>(reinterpret_cast<const uint8_t *>(value.data()));
        |}
        |
        |inline std::size_t string_len(const std::string &value) {
        |  return value.size();
        |}
        |
        |inline std::string string_from_bytes(uint8_t *ptr, std::size_t len) {
        |  if (ptr == nullptr && len != 0) {
        |    error_exit("cosmo0.runtime.string_from_bytes", "null pointer");
        |  }
        |  return std::string(reinterpret_cast<const char *>(ptr), len);
        |}
        |
        |template <typename T, typename E>
        |struct Result {
        |  bool ok = false;
        |  std::optional<T> ok_value{};
        |  std::optional<E> err_value{};
        |
        |  static Result Ok(T value) {
        |    Result result;
        |    result.ok = true;
        |    result.ok_value = std::move(value);
        |    return result;
        |  }
        |
        |  static Result Err(E value) {
        |    Result result;
        |    result.ok = false;
        |    result.err_value = std::move(value);
        |    return result;
        |  }
        |
        |  bool is_ok() const { return ok; }
        |  bool is_err() const { return !ok; }
        |  int32_t tag() const { return ok ? 1 : 0; }
        |};
        |
        |template <typename CommandResult, typename CommandError, typename Command>
        |inline Result<CommandResult, CommandError> command_run(const Command *command) {
        |  if (command == nullptr) {
        |    return Result<CommandResult, CommandError>::Err(CommandError(std::string("null command")));
        |  }
        |
        |  std::string line;
        |  if (command->cwd.has_value()) {
        |    line += "cd ";
        |    line += shell_quote(command->cwd.value().text);
        |    line += " && ";
        |  }
        |
        |  line += shell_quote(command->executable.text);
        |  for (const auto &arg : command->args) {
        |    line += " ";
        |    line += shell_quote(arg);
        |  }
        |  line += " 2>&1";
        |
        |  FILE *pipe = popen(line.c_str(), "r");
        |  if (pipe == nullptr) {
        |    return Result<CommandResult, CommandError>::Err(CommandError(std::string("failed to start command")));
        |  }
        |
        |  std::string output;
        |  char buffer[4096];
        |  while (true) {
        |    const std::size_t count = std::fread(buffer, 1, sizeof(buffer), pipe);
        |    if (count > 0) {
        |      output.append(buffer, count);
        |    }
        |    if (count < sizeof(buffer)) {
        |      if (std::feof(pipe) != 0) {
        |        break;
        |      }
        |      if (std::ferror(pipe) != 0) {
        |        pclose(pipe);
        |        return Result<CommandResult, CommandError>::Err(CommandError(std::string("failed to read command output")));
        |      }
        |    }
        |  }
        |
        |  const int status = command_exit_status(pclose(pipe));
        |  return Result<CommandResult, CommandError>::Ok(CommandResult(status, output, std::string()));
        |}
        |
        |inline std::vector<nlohmann::json> &json_values() {
        |  static std::vector<nlohmann::json> values;
        |  return values;
        |}
        |
        |inline std::string json_store(nlohmann::json value) {
        |  auto &values = json_values();
        |  values.push_back(std::move(value));
        |  return std::to_string(values.size() - 1);
        |}
        |
        |template <typename JsonValue>
        |inline const nlohmann::json &json_ref(const JsonValue *value) {
        |  if (value == nullptr) {
        |    error_exit("cosmo0.runtime.json", "null JsonValue reference");
        |  }
        |  auto index = static_cast<std::size_t>(std::stoull(value->handle));
        |  auto &values = json_values();
        |  if (index >= values.size()) {
        |    error_exit("cosmo0.runtime.json", "invalid JsonValue handle");
        |  }
        |  return values.at(index);
        |}
        |
        |template <typename JsonValue, typename JsonParseError>
        |inline Result<JsonValue, JsonParseError> json_parse(const std::string &text) {
        |  try {
        |    return Result<JsonValue, JsonParseError>::Ok(JsonValue(json_store(nlohmann::json::parse(text))));
        |  } catch (const nlohmann::json::exception &error) {
        |    return Result<JsonValue, JsonParseError>::Err(JsonParseError(std::string(error.what())));
        |  }
        |}
        |
        |template <typename JsonValue>
        |inline bool json_is_null(const JsonValue *value) {
        |  return json_ref(value).is_null();
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<bool> json_as_bool(const JsonValue *value) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_boolean()) {
        |    return std::optional<bool>{};
        |  }
        |  return json.template get<bool>();
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<std::string> json_as_number_text(const JsonValue *value) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_number()) {
        |    return std::optional<std::string>{};
        |  }
        |  return json.dump();
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<std::string> json_as_string(const JsonValue *value) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_string()) {
        |    return std::optional<std::string>{};
        |  }
        |  return json.template get<std::string>();
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<std::size_t> json_array_len(const JsonValue *value) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_array()) {
        |    return std::optional<std::size_t>{};
        |  }
        |  return json.size();
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<JsonValue> json_array_get(const JsonValue *value, std::size_t index) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_array() || index >= json.size()) {
        |    return std::optional<JsonValue>{};
        |  }
        |  return JsonValue(json_store(json.at(index)));
        |}
        |
        |template <typename JsonValue>
        |inline std::optional<JsonValue> json_field(const JsonValue *value, const std::string &key) {
        |  const auto &json = json_ref(value);
        |  if (!json.is_object() || !json.contains(key)) {
        |    return std::optional<JsonValue>{};
        |  }
        |  return JsonValue(json_store(json.at(key)));
        |}
        |
        |template <typename T>
        |struct Arena {
        |  std::vector<T> values{};
        |
        |  std::size_t alloc(T value) {
        |    values.push_back(std::move(value));
        |    return values.size() - 1;
        |  }
        |
        |  const T *get(std::size_t id) const {
        |    return &values.at(id);
        |  }
        |
        |  T *get_mut(std::size_t id) {
        |    return &values.at(id);
        |  }
        |
        |  std::size_t size() const { return values.size(); }
        |  std::size_t len() const { return values.size(); }
        |  bool is_empty() const { return values.empty(); }
        |};
        |
        |template <typename Collection>
        |inline std::size_t &iter_position(const Collection &collection) {
        |  static std::unordered_map<const void *, std::size_t> positions;
        |  return positions[static_cast<const void *>(&collection)];
        |}
        |
        |template <typename T>
        |inline bool iter_has_next(const std::vector<T> &values) {
        |  auto &position = iter_position(values);
        |  if (position < values.size()) {
        |    return true;
        |  }
        |  position = 0;
        |  return false;
        |}
        |
        |template <typename T>
        |inline T iter_next(const std::vector<T> &values) {
        |  auto &position = iter_position(values);
        |  return values.at(position++);
        |}
        |
        |template <typename T>
        |inline bool iter_has_next(const std::set<T> &values) {
        |  auto &position = iter_position(values);
        |  if (position < values.size()) {
        |    return true;
        |  }
        |  position = 0;
        |  return false;
        |}
        |
        |template <typename T>
        |inline T iter_next(const std::set<T> &values) {
        |  auto &position = iter_position(values);
        |  auto it = values.begin();
        |  std::advance(it, static_cast<typename std::set<T>::difference_type>(position++));
        |  return *it;
        |}
        |
        |template <typename K, typename V>
        |inline bool iter_has_next(const std::map<K, V> &values) {
        |  auto &position = iter_position(values);
        |  if (position < values.size()) {
        |    return true;
        |  }
        |  position = 0;
        |  return false;
        |}
        |
        |template <typename K, typename V>
        |inline K iter_next(const std::map<K, V> &values) {
        |  auto &position = iter_position(values);
        |  auto it = values.begin();
        |  std::advance(it, static_cast<typename std::map<K, V>::difference_type>(position++));
        |  return it->first;
        |}
        |
        |template <typename T>
        |inline bool iter_has_next(const Arena<T> &values) {
        |  return iter_has_next(values.values);
        |}
        |
        |template <typename T>
        |inline T iter_next(const Arena<T> &values) {
        |  return iter_next(values.values);
        |}
        |
        |template <typename K, typename V>
        |inline std::optional<V> map_get(const std::map<K, V> &values, const K &key) {
        |  auto it = values.find(key);
        |  if (it == values.end()) {
        |    return std::optional<V>{};
        |  }
        |  return it->second;
        |}
        |
        |template <typename K, typename V>
        |inline std::optional<V> map_insert(std::map<K, V> &values, K key, V value) {
        |  auto it = values.find(key);
        |  if (it == values.end()) {
        |    values.emplace(std::move(key), std::move(value));
        |    return std::optional<V>{};
        |  }
        |  auto previous = it->second;
        |  it->second = std::move(value);
        |  return previous;
        |}
        |
        |} // namespace cosmo0_runtime""".stripMargin

    private def typeForwardDeclarations: List[String] =
      val lines = env.typesById.values.toList.sortBy(_.id.value).map(ty => s"struct ${names.typeName(ty.id)};")
      if lines.isEmpty then Nil else lines :+ ""

    private def typeAliasDeclarations: List[String] =
      val lines = env.declarations.collect { case alias: LirTypeAliasDecl =>
        s"using ${names.aliasName(alias.id)} = ${valueType(alias.target)};"
      }
      if lines.isEmpty then Nil else lines :+ ""

    private def typeDefinitions: List[String] =
      val lines = orderedTypeDefinitions.map(renderTypeDecl)
      if lines.isEmpty then Nil else intersperseBlank(lines) :+ ""

    private def orderedTypeDefinitions: List[LirTypeDecl] =
      val types = env.typesById.values.toList.sortBy(_.id.value)
      val byId = types.map(ty => ty.id -> ty).toMap
      val pending = mutable.LinkedHashMap.from(types.map(ty => ty.id -> ty))
      val emitted = mutable.LinkedHashSet.empty[LirDeclId]
      val result = ListBuffer.empty[LirTypeDecl]

      while pending.nonEmpty do
        val ready = pending.values.find(ty => typeDependencies(ty).forall(emitted.contains))
        ready match
          case Some(ty) =>
            result += ty
            emitted += ty.id
            pending.remove(ty.id)
          case None =>
            val next = pending.values.toList.sortBy(_.id.value).head
            result += next
            emitted += next.id
            pending.remove(next.id)

      result.toList

    private def typeDependencies(ty: LirTypeDecl): Set[LirDeclId] =
      val fieldDeps = ty.fields.flatMap(field => concreteTypeDependencies(field.valueType.source))
      val variantDeps = ty.variants.flatMap { variant =>
        variant.payload.flatMap(payload => concreteTypeDependencies(payload.valueType.source))
      }
      (fieldDeps ++ variantDeps).filterNot(_ == ty.id).toSet

    private def concreteTypeDependencies(valueType: SourceType): Set[LirDeclId] =
      SourceType.dealias(valueType) match
        case SourceType.User(name) =>
          env.typesByName.get(name).map(ty => Set(ty.id)).getOrElse(Set.empty)
        case SourceType.Alias(name, _) =>
          env.aliasesByName.get(name).map(alias => concreteTypeDependencies(alias.target.source)).getOrElse(Set.empty)
        case SourceType.ForeignNamespace(_) | SourceType.ForeignSymbol(_) =>
          Set.empty
        case SourceType.Standard("Id", _ :: Nil) =>
          Set.empty
        case SourceType.Standard("Ptr", _ :: Nil) =>
          Set.empty
        case SourceType.Standard("Box", _ :: Nil) =>
          Set.empty
        case SourceType.Ref(_, _) =>
          Set.empty
        case SourceType.Standard(_, args) =>
          args.flatMap(concreteTypeDependencies).toSet
        case SourceType.Function(params, returnType) =>
          (params :+ returnType).flatMap(concreteTypeDependencies).toSet
        case _ =>
          Set.empty

    private def renderTypeDecl(ty: LirTypeDecl): String =
      val typeName = names.typeName(ty.id)
      val fields = ty.fields.sortBy(_.name)
      val variants = ty.variants.sortBy(_.name)
      val body = ListBuffer.empty[String]
      val drop = dropFunction(ty)
      val ownership = drop.map(renderDropOwnership(ty, fields, _)).getOrElse(Nil)

      if drop.nonEmpty then body += line(2, "mutable bool __cosmo0_drop_active = true;")
      fields.foreach { field =>
        body += line(2, s"${valueType(field.valueType)} ${fieldName(field.name)}{};")
      }

      if variants.nonEmpty then
        variants.foreach { variant =>
          val variantName = variantStructName(variant.name)
          body += line(2, s"struct $variantName {")
          variant.payload.zipWithIndex.foreach { case (payload, index) =>
            body += line(4, s"${valueType(payload.valueType)} ${payloadName(payload, index)}{};")
          }
          if variant.payload.nonEmpty then
            val params = variant.payload.zipWithIndex
              .map { case (payload, index) =>
                s"${valueType(payload.valueType)} arg_${payloadName(payload, index)}"
              }
              .mkString(", ")
            val inits = variant.payload.zipWithIndex
              .map { case (payload, index) =>
                val name = payloadName(payload, index)
                s"$name(std::move(arg_$name))"
              }
              .mkString(", ")
            body += line(4, s"$variantName() = default;")
            body += line(4, s"$variantName($params) : $inits {}")
          body += line(2, "};")
        }
        val variantTypes = variants.map(variant => variantStructName(variant.name)).mkString(", ")
        body += line(2, s"std::variant<$variantTypes> data;")
        body += line(2, "int32_t tag() const { return static_cast<int32_t>(data.index()); }")
        variants.foreach { variant =>
          val variantName = variantStructName(variant.name)
          val params = variant.payload.zipWithIndex
            .map { case (payload, index) =>
              s"${valueType(payload.valueType)} arg_${payloadName(payload, index)}"
            }
            .mkString(", ")
          val args = variant.payload.zipWithIndex
            .map { case (payload, index) => s"std::move(arg_${payloadName(payload, index)})" }
            .mkString(", ")
          val callArgs = if args.nonEmpty then s"($args)" else "{}"
          body += line(2, s"static $typeName make_${safeIdent(variant.name, "variant")}($params) {")
          body += line(4, s"$typeName result;")
          body += line(4, s"result.data = $variantName$callArgs;")
          body += line(4, "return result;")
          body += line(2, "}")
          body += line(2, s"bool is_${safeIdent(variant.name, "variant")}() const {")
          body += line(4, s"return std::holds_alternative<$variantName>(data);")
          body += line(2, "}")
          body += line(2, s"const $variantName &as_${safeIdent(variant.name, "variant")}() const {")
          body += line(4, s"return std::get<$variantName>(data);")
          body += line(2, "}")
        }

      val params = fields.map(field => s"${valueType(field.valueType)} arg_${fieldName(field.name)}")
      val constructor =
        if fields.isEmpty && variants.isEmpty then Nil
        else
          val variantInit = variants.headOption.map(variant => s"data(${variantStructName(variant.name)}{})")
          val fieldInits = fields.map(field => s"${fieldName(field.name)}(std::move(arg_${fieldName(field.name)}))")
          val init = (fieldInits ++ variantInit.toList).mkString(", ")
          val defaultInit = variantInit.fold("")(value => s" : $value")
          val defaultConstructor = line(2, s"$typeName()$defaultInit {}")
          if fields.isEmpty then List(defaultConstructor)
          else List(defaultConstructor, line(2, s"$typeName(${params.mkString(", ")}) : $init {}"))

      val allLines = ListBuffer.empty[String]
      allLines += s"struct $typeName {"
      allLines ++= constructor
      if constructor.nonEmpty && (ownership.nonEmpty || body.nonEmpty) then allLines += ""
      allLines ++= ownership
      if ownership.nonEmpty && body.nonEmpty then allLines += ""
      allLines ++= body
      allLines += "};"
      allLines.mkString("\n")

    private def renderDropOwnership(
        ty: LirTypeDecl,
        fields: List[LirField],
        drop: LirFunction,
    ): List[String] =
      val typeName = names.typeName(ty.id)
      val dropName = names.functionName(drop.id)
      val copyInits = ("__cosmo0_drop_active(other.__cosmo0_drop_active)" +:
        fields.map(field => s"${fieldName(field.name)}(other.${fieldName(field.name)})")).mkString(", ")
      val moveInits = ("__cosmo0_drop_active(other.__cosmo0_drop_active)" +:
        fields.map(field => s"${fieldName(field.name)}(std::move(other.${fieldName(field.name)}))")).mkString(", ")
      val copyAssignments = fields.map(field => s"${fieldName(field.name)} = other.${fieldName(field.name)};")
      val moveAssignments = fields.map(field => s"${fieldName(field.name)} = std::move(other.${fieldName(field.name)});")

      List(
        line(2, s"$typeName(const $typeName &other) : $copyInits {"),
        line(4, s"const_cast<$typeName &>(other).__cosmo0_drop_active = false;"),
        line(2, "}"),
        "",
        line(2, s"$typeName($typeName &&other) noexcept : $moveInits {"),
        line(4, "other.__cosmo0_drop_active = false;"),
        line(2, "}"),
        "",
        line(2, s"$typeName &operator=(const $typeName &other) {"),
        line(4, "if (this != &other) {"),
        line(6, "if (__cosmo0_drop_active) {"),
        line(8, s"$dropName(this);"),
        line(6, "}"),
      ) ++
        copyAssignments.map(line(6, _)) ++
        List(
          line(6, "__cosmo0_drop_active = other.__cosmo0_drop_active;"),
          line(6, s"const_cast<$typeName &>(other).__cosmo0_drop_active = false;"),
          line(4, "}"),
          line(4, "return *this;"),
          line(2, "}"),
          "",
          line(2, s"$typeName &operator=($typeName &&other) noexcept {"),
          line(4, "if (this != &other) {"),
          line(6, "if (__cosmo0_drop_active) {"),
          line(8, s"$dropName(this);"),
          line(6, "}"),
        ) ++
        moveAssignments.map(line(6, _)) ++
        List(
          line(6, "__cosmo0_drop_active = other.__cosmo0_drop_active;"),
          line(6, "other.__cosmo0_drop_active = false;"),
          line(4, "}"),
          line(4, "return *this;"),
          line(2, "}"),
          "",
          line(2, s"~$typeName() {"),
          line(4, "if (__cosmo0_drop_active) {"),
          line(6, s"$dropName(this);"),
          line(4, "}"),
          line(2, "}"),
        )

    private def dropFunction(ty: LirTypeDecl): Option[LirFunction] =
      env.functions.values.find(function =>
        function.owner.contains(ty.id) &&
          function.name == "drop" &&
          function.externBinding.isEmpty &&
          function.returnType.source == SourceType.Unit,
      )

    private def globalDefinitions: List[String] =
      val lines = env.globals.values.toList.sortBy(_.id.value).map { global =>
        val qualifier = if global.mutable then "inline" else "inline const"
        val init = global.initializer.fold(defaultValue(global.valueType))(renderValue)
        s"$qualifier ${valueType(global.valueType)} ${names.globalName(global.id)} = $init;"
      }
      if lines.isEmpty then Nil else lines :+ ""

    private def functionForwardDeclarations: List[String] =
      val lines = env.functions.values.toList.filter(_.externBinding.isEmpty).sortBy(_.id.value).map { function =>
        s"inline ${returnType(function.returnType)} ${names.functionName(function.id)}(${params(function)});"
      }
      if lines.isEmpty then Nil else lines :+ ""

    private def externFunctionDeclarations: List[String] =
      val lines = env.functions.values.toList.flatMap { function =>
        function.externBinding.filter(_.abi == TrustedExternAbi.directCAbiName).map { binding =>
          s"""extern "C" ${returnType(function.returnType)} ${binding.symbol.cppName}(${params(function)});"""
        }
      }.sortBy(identity)
      if lines.isEmpty then Nil else lines :+ ""

    private def functionDefinitions: List[String] =
      intersperseBlank(env.functions.values.toList.filter(_.externBinding.isEmpty).sortBy(_.id.value).map(renderFunction))

    private def renderFunction(function: LirFunction): String =
      val locals = FunctionNames(function)
      val lines = ListBuffer.empty[String]
      lines += s"inline ${returnType(function.returnType)} ${names.functionName(function.id)}(${params(function, locals)}) {"
      function.locals.sortBy(_.id.value).foreach { local =>
        lines += line(2, s"${valueType(local.valueType)} ${locals.local(local.id)}{};")
      }
      if function.blocks.nonEmpty then
        lines += line(2, s"goto ${locals.label(entryBlock(function).label)};")
      function.blocks.sortBy(_.label.value).foreach { block =>
        lines += s"${locals.label(block.label)}:"
        block.operations.foreach(op => lines ++= renderOp(op, function, locals).map(line(2, _)))
        lines ++= renderTerminator(block.terminator, function, locals).map(line(2, _))
      }
      lines += "}"
      lines.mkString("\n")

    private def entryBlock(function: LirFunction): LirBlock =
      function.blocks.find(_.label == Lir.label("entry")).getOrElse(function.blocks.sortBy(_.label.value).head)

    private def params(function: LirFunction): String =
      params(function, FunctionNames(function))

    private def params(function: LirFunction, locals: FunctionNames): String =
      function.params
        .map(param => s"${valueType(param.valueType)} ${locals.local(param.id)}")
        .mkString(", ")

    private def renderOp(
        op: LirOp,
        function: LirFunction,
        locals: FunctionNames,
    ): List[String] =
      op match
        case LirAllocLocal(local, init) =>
          init.map(value => List(s"${locals.local(local.id)} = ${renderValue(value, locals)};")).getOrElse(Nil)

        case LirAssign(target, value) =>
          List(s"${renderPlace(target, locals)} = ${renderValue(value, locals)};")

        case LirFieldGet(output, receiver, field, _) =>
          List(s"${locals.local(output)} = ${fieldAccess(receiver, field, locals)};")

        case LirFieldSet(receiver, field, value) =>
          List(s"${fieldAccess(receiver, field, locals)} = ${renderValue(value, locals)};")

        case LirDirectCall(output, callee, args, _) =>
          env.functions.get(callee).flatMap(_.externBinding) match
            case Some(binding) =>
              emitExternCall(output, callee, binding, args, locals)
            case None =>
              val invocation = s"${names.functionName(callee)}(${args.map(renderValue(_, locals)).mkString(", ")})"
              assignOrStatement(output, invocation, locals)

        case LirLoweredMethodCall(output, receiver, method, args, _) =>
          methodFunction(receiver, method) match
            case Some(target) =>
              val receiverArg = methodReceiverArg(receiver, target, locals)
              val invocation = s"${names.functionName(target.id)}(${(receiverArg :: args.map(renderValue(_, locals))).mkString(", ")})"
              assignOrStatement(output, invocation, locals)
            case None =>
              unsupportedDescriptor(s"method", method, s"no lowered method target for ${receiver.valueType.display}.$method")
              Nil

        case LirDescriptorIntrinsic(output, descriptor, name, args, _) =>
          emitDescriptor(descriptor, name, args, locals) match
            case Some(EmittedDescriptor.Expr(value, needed)) =>
              requirements ++= needed.map(BackendRequirement.descriptor)
              assignOrStatement(output, value, locals)
            case Some(EmittedDescriptor.Stmt(value, needed)) =>
              requirements ++= needed.map(BackendRequirement.descriptor)
              output match
                case Some(id) =>
                  unsupportedDescriptor(descriptorText(descriptor), name, s"operation writes no value for $id")
                  Nil
                case None =>
                  List(s"$value;")
            case None =>
              Nil

        case LirConstructType(output, owner, fields) =>
          constructType(output, owner, fields, locals)

        case LirConstructVariant(output, owner, variant, payload) =>
          constructVariant(owner, variant, payload, locals) match
            case Some(value) => List(s"${locals.local(output)} = $value;")
            case None        => Nil

        case LirReadVariantTag(output, scrutinee, owner) =>
          variantTag(scrutinee, owner, locals) match
            case Some(value) => List(s"${locals.local(output)} = $value;")
            case None        => Nil

        case LirCheckVariantTag(output, scrutinee, owner, variant) =>
          checkVariant(scrutinee, owner, variant, locals) match
            case Some(value) => List(s"${locals.local(output)} = $value;")
            case None        => Nil

        case LirReadVariantPayload(output, scrutinee, variant, index, _) =>
          readVariantPayload(scrutinee, variant, index, locals) match
            case Some(value) => List(s"${locals.local(output)} = $value;")
            case None        => Nil

    private def renderTerminator(
        terminator: LirTerminator,
        function: LirFunction,
        locals: FunctionNames,
    ): List[String] =
      terminator match
        case LirReturn(value) =>
          function.returnType.source match
            case SourceType.Unit =>
              List("return;")
            case _ =>
              value.map(value => List(s"return ${renderValue(value, locals)};")).getOrElse(List("return {};"))

        case LirBranch(target) =>
          List(s"goto ${locals.label(target)};")

        case LirCondBranch(condition, trueTarget, falseTarget) =>
          List(
            s"if (${renderValue(condition, locals)}) {",
            line(2, s"goto ${locals.label(trueTarget)};"),
            "} else {",
            line(2, s"goto ${locals.label(falseTarget)};"),
            "}",
          )

        case LirUnreachable(reason) =>
          List(s"cosmo0_runtime::unreachable(${reason.fold("nullptr")(quote)});")

        case LirErrorExit(code, message) =>
          List(s"cosmo0_runtime::error_exit(${quote(code)}, ${message.fold("nullptr")(quote)});")

    private def assignOrStatement(
        output: Option[LirLocalId],
        expression: String,
        locals: FunctionNames,
    ): List[String] =
      output match
        case Some(id) => List(s"${locals.local(id)} = $expression;")
        case None     => List(s"$expression;")

    private def emitExternCall(
        output: Option[LirLocalId],
        callee: LirDeclId,
        binding: LirExternBinding,
        args: List[LirValue],
        locals: FunctionNames,
    ): List[String] =
      requirements ++= binding.requirements
      if binding.abi != TrustedExternAbi.directCAbiName && !supportedExternSymbols.contains(binding.symbol) then
        missingExternRuntimeSymbol(callee, binding)
        Nil
      else
        val invocation =
          if binding.symbol == CppQualifiedSymbol.global("cosmo0_runtime", "json_parse") then
            jsonParseInvocation(callee, binding, args, locals)
          else if binding.symbol == CppQualifiedSymbol.global("cosmo0_runtime", "command_run") then
            commandRunInvocation(callee, binding, args, locals)
          else s"${binding.symbol.cppName}(${args.map(renderValue(_, locals)).mkString(", ")})"
        assignOrStatement(output, invocation, locals)

    private def jsonParseInvocation(
        callee: LirDeclId,
        binding: LirExternBinding,
        args: List[LirValue],
        locals: FunctionNames,
    ): String =
      val templateArgs =
        env.functions.get(callee).map(_.returnType.source) match
          case Some(SourceType.Standard("Result", ok :: err :: Nil)) =>
            s"<${valueTypeName(ok)}, ${valueTypeName(err)}>"
          case _ =>
            ""
      s"${binding.symbol.cppName}$templateArgs(${args.map(renderValue(_, locals)).mkString(", ")})"

    private def commandRunInvocation(
        callee: LirDeclId,
        binding: LirExternBinding,
        args: List[LirValue],
        locals: FunctionNames,
    ): String =
      val templateArgs =
        env.functions.get(callee).map(_.returnType.source) match
          case Some(SourceType.Standard("Result", ok :: err :: Nil)) =>
            s"<${valueTypeName(ok)}, ${valueTypeName(err)}>"
          case _ =>
            ""
      s"${binding.symbol.cppName}$templateArgs(${args.map(renderValue(_, locals)).mkString(", ")})"

    private def renderPlace(place: LirPlace, locals: FunctionNames): String =
      place match
        case LirLocalPlace(id, _) =>
          locals.local(id)
        case LirFieldPlace(receiver, field, _) =>
          fieldAccess(receiver, field, locals)

    private def fieldAccess(receiver: LirValue, field: String, locals: FunctionNames): String =
      val op =
        SourceType.dealias(receiver.valueType.source) match
          case SourceType.Ref(_, _) => "->"
          case _                    => "."
      s"${renderValue(receiver, locals)}$op${fieldName(field)}"

    private def renderValue(value: LirValue): String =
      renderValue(value, FunctionNames.empty)

    private def renderValue(value: LirValue, locals: FunctionNames): String =
      value match
        case LirUnitValue =>
          "std::monostate{}"
        case LirBoolValue(value) =>
          if value then "true" else "false"
        case LirIntValue(value, valueType) =>
          s"static_cast<${valueTypeName(valueType)}>(${value.toString})"
        case LirFloatValue(value, valueType) =>
          s"static_cast<${valueTypeName(valueType)}>(${value.toString})"
        case LirStringValue(value) =>
          s"std::string(${quote(value)})"
        case LirCharValue(value) =>
          s"static_cast<char32_t>(${value.toInt})"
        case LirLocalRef(id, _) =>
          locals.local(id)
        case LirGlobalRef(id, _) =>
          names.globalName(id)
        case LirFunctionRef(id, _) =>
          names.functionName(id)
        case LirBorrowValue(value, _) =>
          s"&${renderValue(value, locals)}"
        case LirDerefValue(value, _) =>
          s"(*${renderValue(value, locals)})"
        case LirFieldRef(receiver, field, _) =>
          fieldAccess(receiver, field, locals)

    private def defaultValue(valueType: LirTypeRef): String =
      SourceType.dealias(valueType.source) match
        case SourceType.Unit => "std::monostate{}"
        case _               => s"${valueTypeName(valueType)}{}"

    private def returnType(valueType: LirTypeRef): String =
      SourceType.dealias(valueType.source) match
        case SourceType.Unit => "void"
        case _               => valueTypeName(valueType)

    private def valueType(valueType: LirTypeRef): String =
      valueTypeName(valueType)

    private def valueTypeName(valueType: LirTypeRef): String =
      valueTypeName(valueType.source)

    private def valueTypeName(valueType: SourceType): String =
      SourceType.dealias(valueType) match
        case SourceType.Builtin("Unit")          => "std::monostate"
        case SourceType.Builtin("Bool")          => "bool"
        case SourceType.Builtin("i8")            => "int8_t"
        case SourceType.Builtin("i16")           => "int16_t"
        case SourceType.Builtin("i32")           => "int32_t"
        case SourceType.Builtin("i64")           => "int64_t"
        case SourceType.Builtin("u8")            => "uint8_t"
        case SourceType.Builtin("u16")           => "uint16_t"
        case SourceType.Builtin("u32")           => "uint32_t"
        case SourceType.Builtin("u64")           => "uint64_t"
        case SourceType.Builtin("usize")         => "std::size_t"
        case SourceType.Builtin("String")        => "std::string"
        case SourceType.Builtin("Char")          => "char32_t"
        case SourceType.Builtin("f32")           => "float"
        case SourceType.Builtin("f64")           => "double"
        case SourceType.User(name) =>
          env.typesByName.get(name).map(ty => names.typeName(ty.id)).getOrElse(safeIdent(name, "type"))
        case SourceType.Alias(name, _) =>
          env.aliasesByName.get(name).map(alias => names.aliasName(alias.id)).getOrElse(safeIdent(name, "alias"))
        case SourceType.ForeignNamespace(value) =>
          unsupportedType(SourceType.ForeignNamespace(value))
          "std::monostate"
        case SourceType.ForeignSymbol(canonicalName) =>
          canonicalName
        case SourceType.Ref(target, true) =>
          s"${valueTypeName(target)} *"
        case SourceType.Ref(target, false) =>
          s"const ${valueTypeName(target)} *"
        case SourceType.Standard("Vec", item :: Nil) =>
          s"std::vector<${valueTypeName(item)}>"
        case SourceType.Standard("Option", item :: Nil) =>
          s"std::optional<${valueTypeName(item)}>"
        case SourceType.Standard("Result", ok :: err :: Nil) =>
          s"cosmo0_runtime::Result<${valueTypeName(ok)}, ${valueTypeName(err)}>"
        case SourceType.Standard("Map", key :: value :: Nil) =>
          s"std::map<${valueTypeName(key)}, ${valueTypeName(value)}>"
        case SourceType.Standard("Set", item :: Nil) =>
          s"std::set<${valueTypeName(item)}>"
        case SourceType.Standard("Arena", item :: Nil) =>
          s"cosmo0_runtime::Arena<${valueTypeName(item)}>"
        case SourceType.Standard("Id", _ :: Nil) =>
          "std::size_t"
        case SourceType.Standard("Ptr", item :: Nil) =>
          s"${valueTypeName(item)} *"
        case SourceType.Standard("Box", item :: Nil) =>
          s"${valueTypeName(item)} *"
        case SourceType.Function(_, _) =>
          "void *"
        case SourceType.Never =>
          "std::monostate"
        case SourceType.Error =>
          "std::monostate"
        case other =>
          unsupportedType(other)
          "std::monostate"

    private def methodFunction(receiver: LirValue, method: String): Option[LirFunction] =
      SourceType.dealias(SourceType.deref(receiver.valueType.source)) match
        case SourceType.User(name) =>
          env.typesByName.get(name).flatMap { owner =>
            env.functions.values.find(function => function.owner.contains(owner.id) && function.name == method)
          }
        case _ =>
          None

    private def methodReceiverArg(
        receiver: LirValue,
        method: LirFunction,
        locals: FunctionNames,
    ): String =
      val rendered = renderValue(receiver, locals)
      method.params.headOption.map(_.valueType.source) match
        case Some(SourceType.Ref(_, _)) =>
          SourceType.dealias(receiver.valueType.source) match
            case SourceType.Ref(_, _) => rendered
            case _                    => s"&$rendered"
        case _ =>
          rendered

    private def emitDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      descriptor.name match
        case name0 if numericDescriptors.contains(name0) =>
          emitNumericDescriptor(name, args, locals, descriptor)

        case "Bool" =>
          emitBoolDescriptor(name, args, locals, descriptor)

        case "Char" =>
          emitCharDescriptor(name, args, locals, descriptor)

        case "String" =>
          emitStringDescriptor(name, args, locals, descriptor)

        case "Vec" =>
          emitVecDescriptor(descriptor, name, args, locals)

        case "Option" =>
          emitOptionDescriptor(descriptor, name, args, locals)

        case "Result" =>
          emitResultDescriptor(descriptor, name, args, locals)

        case "Map" =>
          emitMapDescriptor(descriptor, name, args, locals)

        case "Set" =>
          emitSetDescriptor(descriptor, name, args, locals)

        case "Arena" =>
          emitArenaDescriptor(descriptor, name, args, locals)

        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitNumericDescriptor(
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
        descriptor: LirDescriptorRef,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "neg" if args.length == 1 => Some(EmittedDescriptor.Expr(s"(-${arg(0)})", Set("numeric")))
        case "add" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} + ${arg(1)})", Set("numeric")))
        case "sub" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} - ${arg(1)})", Set("numeric")))
        case "mul" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} * ${arg(1)})", Set("numeric")))
        case "div" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} / ${arg(1)})", Set("numeric")))
        case "mod" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} % ${arg(1)})", Set("numeric")))
        case "eq" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} == ${arg(1)})", Set("numeric")))
        case "ne" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} != ${arg(1)})", Set("numeric")))
        case "lt" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} < ${arg(1)})", Set("numeric")))
        case "le" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} <= ${arg(1)})", Set("numeric")))
        case "gt" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} > ${arg(1)})", Set("numeric")))
        case "ge" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} >= ${arg(1)})", Set("numeric")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitBoolDescriptor(
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
        descriptor: LirDescriptorRef,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "not" if args.length == 1 => Some(EmittedDescriptor.Expr(s"(!${arg(0)})", Set("bool")))
        case "and" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} && ${arg(1)})", Set("bool")))
        case "or" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} || ${arg(1)})", Set("bool")))
        case "eq" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} == ${arg(1)})", Set("bool")))
        case "ne" if args.length == 2  => Some(EmittedDescriptor.Expr(s"(${arg(0)} != ${arg(1)})", Set("bool")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitCharDescriptor(
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
        descriptor: LirDescriptorRef,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "eq" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} == ${arg(1)})", Set("char")))
        case "ne" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} != ${arg(1)})", Set("char")))
        case "lt" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} < ${arg(1)})", Set("char")))
        case "le" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} <= ${arg(1)})", Set("char")))
        case "gt" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} > ${arg(1)})", Set("char")))
        case "ge" if args.length == 2 => Some(EmittedDescriptor.Expr(s"(${arg(0)} >= ${arg(1)})", Set("char")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitStringDescriptor(
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
        descriptor: LirDescriptorRef,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "size" | "len" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.size()", Set("string")))
        case "is_empty" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.empty()", Set("string")))
        case "slice" if args.length == 3 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.substr(${arg(1)}, ${arg(2)} - ${arg(1)})", Set("string")))
        case "char_at" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"static_cast<char32_t>(${arg(0)}.at(${arg(1)}))", Set("string")))
        case "byte_at" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"static_cast<uint8_t>(${arg(0)}.at(${arg(1)}))", Set("string")))
        case "concat" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"(${arg(0)} + ${arg(1)})", Set("string")))
        case "eq" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"(${arg(0)} == ${arg(1)})", Set("string")))
        case "ne" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"(${arg(0)} != ${arg(1)})", Set("string")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitVecDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      val ownerType = descriptorOwnerType(descriptor)
      name match
        case "<init>" if args.isEmpty =>
          Some(EmittedDescriptor.Expr(s"${valueTypeName(ownerType)}{}", Set("vec")))
        case "push" if args.length == 2 =>
          Some(EmittedDescriptor.Stmt(s"${arg(0)}.push_back(${arg(1)})", Set("vec")))
        case "get" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.at(${arg(1)})", Set("vec")))
        case "set" if args.length == 3 =>
          Some(EmittedDescriptor.Stmt(s"${arg(0)}.at(${arg(1)}) = ${arg(2)}", Set("vec")))
        case "size" | "len" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.size()", Set("vec")))
        case "is_empty" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.empty()", Set("vec")))
        case "iter_has_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_has_next(${arg(0)})", Set("vec.iter")))
        case "iter_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_next(${arg(0)})", Set("vec.iter")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitOptionDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "is_some" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.has_value()", Set("option")))
        case "is_none" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"!${arg(0)}.has_value()", Set("option")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitResultDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      name match
        case "is_ok" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.is_ok()", Set("result")))
        case "is_err" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.is_err()", Set("result")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitMapDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      val ownerType = descriptorOwnerType(descriptor)
      name match
        case "<init>" if args.isEmpty =>
          Some(EmittedDescriptor.Expr(s"${valueTypeName(ownerType)}{}", Set("map")))
        case "get" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::map_get(${arg(0)}, ${arg(1)})", Set("map")))
        case "insert" if args.length == 3 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::map_insert(${arg(0)}, ${arg(1)}, ${arg(2)})", Set("map")))
        case "contains" | "contains_key" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"(${arg(0)}.find(${arg(1)}) != ${arg(0)}.end())", Set("map")))
        case "size" | "len" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.size()", Set("map")))
        case "is_empty" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.empty()", Set("map")))
        case "iter_has_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_has_next(${arg(0)})", Set("map.iter")))
        case "iter_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_next(${arg(0)})", Set("map.iter")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitSetDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      val ownerType = descriptorOwnerType(descriptor)
      name match
        case "<init>" if args.isEmpty =>
          Some(EmittedDescriptor.Expr(s"${valueTypeName(ownerType)}{}", Set("set")))
        case "insert" if args.length == 2 =>
          Some(EmittedDescriptor.Stmt(s"${arg(0)}.insert(${arg(1)})", Set("set")))
        case "contains" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"(${arg(0)}.find(${arg(1)}) != ${arg(0)}.end())", Set("set")))
        case "size" | "len" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.size()", Set("set")))
        case "is_empty" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.empty()", Set("set")))
        case "iter_has_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_has_next(${arg(0)})", Set("set.iter")))
        case "iter_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_next(${arg(0)})", Set("set.iter")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def emitArenaDescriptor(
        descriptor: LirDescriptorRef,
        name: String,
        args: List[LirValue],
        locals: FunctionNames,
    ): Option[EmittedDescriptor] =
      def arg(index: Int): String = renderValue(args(index), locals)
      val ownerType = descriptorOwnerType(descriptor)
      name match
        case "<init>" if args.isEmpty =>
          Some(EmittedDescriptor.Expr(s"${valueTypeName(ownerType)}{}", Set("arena")))
        case "alloc" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.alloc(${arg(1)})", Set("arena")))
        case "get" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.get(${arg(1)})", Set("arena")))
        case "get_mut" if args.length == 2 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.get_mut(${arg(1)})", Set("arena")))
        case "size" | "len" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"${arg(0)}.size()", Set("arena")))
        case "iter_has_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_has_next(${arg(0)})", Set("arena.iter")))
        case "iter_next" if args.length == 1 =>
          Some(EmittedDescriptor.Expr(s"cosmo0_runtime::iter_next(${arg(0)})", Set("arena.iter")))
        case _ =>
          unsupportedDescriptor(descriptorText(descriptor), name)
          None

    private def constructVariant(
        owner: LirTypeRef,
        variant: String,
        payload: List[LirValue],
        locals: FunctionNames,
    ): Option[String] =
      SourceType.dealias(owner.source) match
        case SourceType.Standard("Option", item :: Nil) =>
          variant match
            case "Some" if payload.length == 1 =>
              Some(s"std::optional<${valueTypeName(item)}>(${renderValue(payload.head, locals)})")
            case "None" if payload.isEmpty =>
              Some(s"std::optional<${valueTypeName(item)}>{}")
            case _ =>
              unsupportedDescriptor(owner.display, variant, "unsupported Option variant")
              None
        case SourceType.Standard("Result", ok :: err :: Nil) =>
          variant match
            case "Ok" if payload.length == 1 =>
              Some(s"cosmo0_runtime::Result<${valueTypeName(ok)}, ${valueTypeName(err)}>::Ok(${renderValue(payload.head, locals)})")
            case "Err" if payload.length == 1 =>
              Some(s"cosmo0_runtime::Result<${valueTypeName(ok)}, ${valueTypeName(err)}>::Err(${renderValue(payload.head, locals)})")
            case _ =>
              unsupportedDescriptor(owner.display, variant, "unsupported Result variant")
              None
        case SourceType.User(name) =>
          env.typesByName.get(name) match
            case Some(ty) =>
              val args = payload.map(renderValue(_, locals)).mkString(", ")
              Some(s"${names.typeName(ty.id)}::make_${safeIdent(variant, "variant")}($args)")
            case None =>
              unsupportedType(owner.source)
              None
        case _ =>
          unsupportedType(owner.source)
          None

    private def constructType(
        output: LirLocalId,
        owner: LirTypeRef,
        fields: List[LirFieldInit],
        locals: FunctionNames,
    ): List[String] =
      SourceType.dealias(owner.source) match
        case SourceType.User(name) =>
          env.typesByName.get(name) match
            case Some(ty) =>
              val target = locals.local(output)
              s"$target = ${names.typeName(ty.id)}{};" ::
                fields.map(field => s"$target.${fieldName(field.name)} = ${renderValue(field.value, locals)};")
            case None =>
              unsupportedType(owner.source)
              Nil
        case _ =>
          unsupportedType(owner.source)
          Nil

    private def variantTag(
        scrutinee: LirValue,
        owner: LirTypeRef,
        locals: FunctionNames,
    ): Option[String] =
      SourceType.dealias(owner.source) match
        case SourceType.Standard("Option", _ :: Nil) =>
          Some(s"(${renderValue(scrutinee, locals)}.has_value() ? 1 : 0)")
        case SourceType.Standard("Result", _ :: _ :: Nil) =>
          Some(s"${renderValue(scrutinee, locals)}.tag()")
        case SourceType.User(name) =>
          env.typesByName.get(name).map(_ => s"${renderValue(scrutinee, locals)}.tag()")
        case _ =>
          unsupportedType(owner.source)
          None

    private def checkVariant(
        scrutinee: LirValue,
        owner: LirTypeRef,
        variant: String,
        locals: FunctionNames,
    ): Option[String] =
      SourceType.dealias(owner.source) match
        case SourceType.Standard("Option", _ :: Nil) =>
          variant match
            case "Some" => Some(s"${renderValue(scrutinee, locals)}.has_value()")
            case "None" => Some(s"!${renderValue(scrutinee, locals)}.has_value()")
            case _ =>
              unsupportedDescriptor(owner.display, variant, "unsupported Option variant")
              None
        case SourceType.Standard("Result", _ :: _ :: Nil) =>
          variant match
            case "Ok"  => Some(s"${renderValue(scrutinee, locals)}.is_ok()")
            case "Err" => Some(s"${renderValue(scrutinee, locals)}.is_err()")
            case _ =>
              unsupportedDescriptor(owner.display, variant, "unsupported Result variant")
              None
        case SourceType.User(name) =>
          env.typesByName.get(name) match
            case Some(_) => Some(s"${renderValue(scrutinee, locals)}.is_${safeIdent(variant, "variant")}()")
            case None =>
              unsupportedType(owner.source)
              None
        case _ =>
          unsupportedType(owner.source)
          None

    private def readVariantPayload(
        scrutinee: LirValue,
        variant: String,
        index: Int,
        locals: FunctionNames,
    ): Option[String] =
      SourceType.dealias(SourceType.deref(scrutinee.valueType.source)) match
        case SourceType.Standard("Option", _ :: Nil) if variant == "Some" && index == 0 =>
          Some(s"${renderValue(scrutinee, locals)}.value()")
        case SourceType.Standard("Result", _ :: _ :: Nil) if variant == "Ok" && index == 0 =>
          Some(s"${renderValue(scrutinee, locals)}.ok_value.value()")
        case SourceType.Standard("Result", _ :: _ :: Nil) if variant == "Err" && index == 0 =>
          Some(s"${renderValue(scrutinee, locals)}.err_value.value()")
        case SourceType.User(name) =>
          env.typesByName.get(name) match
            case Some(ty) =>
              ty.variants.find(_.name == variant).flatMap(_.payload.lift(index)) match
                case Some(payload) =>
                  Some(s"${renderValue(scrutinee, locals)}.as_${safeIdent(variant, "variant")}().${payloadName(payload, index)}")
                case None =>
                  unsupportedDescriptor(name, variant, s"payload index $index is unavailable")
                  None
            case None =>
              unsupportedType(scrutinee.valueType.source)
              None
        case _ =>
          unsupportedType(scrutinee.valueType.source)
          None

    private def mainWrapper: Option[String] =
      env.functions.values
        .find(function =>
          function.externBinding.isEmpty &&
            function.owner.isEmpty &&
            function.name == "main" &&
            isRunnableMain(function)
        )
        .map { main =>
          val qualified = (namespace :+ names.functionName(main.id)).mkString("::")
          val parameterList = if main.params.isEmpty then "" else "int argc, char **argv"
          val invocation =
            if main.params.isEmpty then s"$qualified()"
            else s"$qualified(cosmo0_runtime::argv_strings(argc, argv))"
          SourceType.dealias(main.returnType.source) match
            case SourceType.Unit =>
              s"""int main($parameterList) {
                 |  $invocation;
                 |  return 0;
                 |}""".stripMargin
            case _ =>
              s"""int main($parameterList) {
                 |  return static_cast<int>($invocation);
                 |}""".stripMargin
        }

    private def isRunnableMain(function: LirFunction): Boolean =
      function.params.isEmpty ||
        (function.params match
          case param :: Nil =>
            SourceType.same(
              param.valueType.source,
              SourceType.Standard("Vec", List(SourceType.String))
            )
          case _            => false)

    private def descriptorOwnerType(descriptor: LirDescriptorRef): SourceType =
      SourceType.scalar(descriptor.name).filter(_ => descriptor.args.isEmpty).getOrElse {
        SourceType.Standard(descriptor.name, descriptor.args.map(_.source))
      }

    private def descriptorText(descriptor: LirDescriptorRef): String =
      if descriptor.args.isEmpty then descriptor.name
      else s"${descriptor.name}[${descriptor.args.map(_.display).mkString(", ")}]"

    private def unsupportedDescriptor(
        descriptor: String,
        operation: String,
        detail: String = "",
    ): Unit =
      val suffix = if detail.nonEmpty then s": $detail" else ""
      errors += Diagnostic(
        Phase.Compile,
        DiagnosticSeverity.Error,
        "cosmo0.cpp.unsupported-descriptor",
        s"C++ backend does not support descriptor $descriptor::$operation$suffix",
      )

    private def missingExternRuntimeSymbol(
        callee: LirDeclId,
        binding: LirExternBinding,
    ): Unit =
      errors += Diagnostic(
        Phase.Compile,
        DiagnosticSeverity.Error,
        "cosmo0.cpp.missing-extern-runtime-symbol",
        s"C++ backend has no runtime symbol ${binding.symbol.canonical} for extern function $callee",
      )

    private def unsupportedType(valueType: SourceType): Unit =
      errors += Diagnostic(
        Phase.Compile,
        DiagnosticSeverity.Error,
        "cosmo0.cpp.unsupported-type",
        s"C++ backend does not support type ${valueType.display}",
      )

    private final class FunctionNames(function: LirFunction):
      private val localNames =
        uniqueNames(
          (function.params.map(param => param.id -> param.name) ++
            function.locals.map(local => local.id -> local.name)).sortBy(_._1.value),
          "v",
          _.value,
        )
      private val labelNames =
        uniqueNames(function.blocks.map(block => block.label -> block.label.value).sortBy(_._1.value), "bb", _.value)

      def local(id: LirLocalId): String =
        localNames.getOrElse(id, safeIdent(id.value, "v"))

      def label(label: LirLabel): String =
        labelNames.getOrElse(label, safeIdent(label.value, "bb"))

    private object FunctionNames:
      def apply(function: LirFunction): FunctionNames =
        new FunctionNames(function)

      val empty: FunctionNames =
        FunctionNames(
          LirFunction(
            Lir.declId("empty"),
            "empty",
            Nil,
            Lir.t(SourceType.Unit),
            Nil,
            Nil,
          ),
        )

    private final class BackendNames(env: DeclEnv):
      private val typeNames =
        uniqueNames(env.typesById.values.toList.map(ty => ty.id -> ty.name).sortBy(_._1.value), "T", _.value)
      private val aliasNames =
        uniqueNames(
          env.declarations.collect { case alias: LirTypeAliasDecl => alias.id -> alias.name },
          "A",
          _.value,
        )
      private val globalNames =
        uniqueNames(env.globals.values.toList.map(global => global.id -> global.name).sortBy(_._1.value), "g", _.value)
      private val functionNames =
        uniqueNames(
          env.functions.values.toList
            .map(function => function.id -> function.owner.fold(function.name)(owner => s"${owner.value}.${function.name}"))
            .sortBy(_._1.value),
          "fn",
          _.value,
        )

      def typeName(id: LirDeclId): String =
        typeNames.getOrElse(id, safeIdent(id.value, "T"))

      def aliasName(id: LirDeclId): String =
        aliasNames.getOrElse(id, safeIdent(id.value, "A"))

      def globalName(id: LirDeclId): String =
        globalNames.getOrElse(id, safeIdent(id.value, "g"))

      def functionName(id: LirDeclId): String =
        functionNames.getOrElse(id, safeIdent(id.value, "fn"))

    private object BackendNames:
      def apply(env: DeclEnv): BackendNames =
        new BackendNames(env)

    private def uniqueNames[K](
        values: List[(K, String)],
        prefix: String,
        keyText: K => String,
    ): Map[K, String] =
      val used = mutable.LinkedHashMap.empty[String, Int]
      values.foldLeft(Map.empty[K, String]) { case (acc, (key, raw)) =>
        val base = safeIdent(raw, prefix)
        val count = used.getOrElse(base, 0)
        used.update(base, count + 1)
        val value =
          if count == 0 then base
          else s"${base}_${stableHash(keyText(key))}"
        acc.updated(key, value)
      }

    private def stableHash(value: String): String =
      val raw = value.foldLeft(0x811c9dc5) { (hash, char) =>
        (hash ^ char.toInt) * 0x01000193
      }
      java.lang.Integer.toUnsignedString(raw, 36)

    private def fieldName(value: String): String =
      safeIdent(value, "field")

    private def payloadName(payload: LirVariantPayload, index: Int): String =
      payload.name.fold(s"field$index")(fieldName)

    private def variantStructName(value: String): String =
      s"Variant_${safeIdent(value, "case")}"

    private def safeIdent(value: String, fallback: String): String =
      val builder = new StringBuilder
      value.foreach { char =>
        if char.isLetterOrDigit || char == '_' then builder.append(char)
        else if builder.nonEmpty && builder.last != '_' then builder.append('_')
      }
      val raw = builder.toString.stripPrefix("_").stripSuffix("_")
      val base = if raw.nonEmpty then raw else fallback
      val prefixed =
        if base.headOption.exists(_.isDigit) then s"${fallback}_$base"
        else base
      if cppKeywords.contains(prefixed) then s"${prefixed}_"
      else prefixed

    private def quote(value: String): String =
      val builder = new StringBuilder
      builder.append('"')
      value.foreach {
        case '\\' => builder.append("\\\\")
        case '"'  => builder.append("\\\"")
        case '\n' => builder.append("\\n")
        case '\r' => builder.append("\\r")
        case '\t' => builder.append("\\t")
        case char if char.isControl =>
          builder.append("\\x")
          builder.append(f"${char.toInt}%02x")
        case char =>
          builder.append(char)
      }
      builder.append('"')
      builder.toString

    private def line(indent: Int, text: String): String =
      (" " * indent) + text

    private def intersperseBlank(values: List[String]): List[String] =
      values.flatMap(value => List(value, "")).dropRight(1)

    private lazy val numericDescriptors: Set[String] =
      Set("i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "usize", "f32", "f64")

    private lazy val supportedExternSymbols: Set[CppQualifiedSymbol] =
      Set(
        CppQualifiedSymbol.global("cosmo0_runtime", "print"),
        CppQualifiedSymbol.global("cosmo0_runtime", "println"),
        CppQualifiedSymbol.global("cosmo0_runtime", "read_file"),
        CppQualifiedSymbol.global("cosmo0_runtime", "read_dir"),
        CppQualifiedSymbol.global("cosmo0_runtime", "path_is_file"),
        CppQualifiedSymbol.global("cosmo0_runtime", "path_is_dir"),
        CppQualifiedSymbol.global("cosmo0_runtime", "write_file"),
        CppQualifiedSymbol.global("cosmo0_runtime", "string_data"),
        CppQualifiedSymbol.global("cosmo0_runtime", "string_len"),
        CppQualifiedSymbol.global("cosmo0_runtime", "string_from_bytes"),
        CppQualifiedSymbol.global("cosmo0_runtime", "command_run"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_parse"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_is_null"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_as_bool"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_as_number_text"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_as_string"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_array_len"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_array_get"),
        CppQualifiedSymbol.global("cosmo0_runtime", "json_field"),
      )

    private lazy val cppKeywords: Set[String] =
      Set(
        "alignas",
        "alignof",
        "and",
        "asm",
        "auto",
        "bitand",
        "bitor",
        "bool",
        "break",
        "case",
        "catch",
        "char",
        "class",
        "compl",
        "const",
        "constexpr",
        "continue",
        "decltype",
        "default",
        "delete",
        "do",
        "double",
        "else",
        "enum",
        "explicit",
        "export",
        "extern",
        "false",
        "float",
        "for",
        "friend",
        "goto",
        "if",
        "inline",
        "int",
        "long",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "not",
        "operator",
        "or",
        "private",
        "protected",
        "public",
        "register",
        "return",
        "short",
        "signed",
        "sizeof",
        "static",
        "struct",
        "switch",
        "template",
        "this",
        "throw",
        "true",
        "try",
        "typedef",
        "typename",
        "union",
        "unsigned",
        "using",
        "virtual",
        "void",
        "volatile",
        "while",
        "xor",
      )
