package cosmo0

class LspTypesPackageTests extends munit.FunSuite:
  test("lsp-types generator package compiles as the full metamodel generator"):
    val path = "packages/lsp-types"
    val loaded = Cosmo0().loadPackage(path)

    assertEquals(loaded.phase, Phase.Check)
    assert(
      loaded.isSuccess,
      s"lsp-types package load failed with diagnostics: ${loaded.diagnostics.map(d => d.code -> d.message)}",
    )
    assertEquals(loaded.value.get.metadata.stageProfile, Some(StageCapabilityRegistry.Cosmo1Stage1))
    assertEquals(
      loaded.value.get.modules.map(_.modulePath),
      List(
        List("generator", "full_emit"),
        List("generator", "metamodel"),
        List("main"),
        List("std", "bytes"),
        List("std", "char_class"),
        List("std", "char_class_test"),
        List("std", "json"),
        List("std", "json_test"),
        List("std", "map_set"),
        List("std", "map_set_test"),
        List("std", "path_fs"),
        List("std", "text"),
        List("std", "text_output"),
        List("types_test"),
      ),
    )

    val compiled = Cosmo0().compileRunnablePackage(path)

    assertEquals(compiled.phase, Phase.Compile)
    assert(
      compiled.isSuccess,
      s"lsp-types package compile failed with diagnostics: ${compiled.diagnostics.map(d => d.code -> d.message)}",
    )
    val output = compiled.value.get.output
    assertEquals(output.moduleName, "cosmo_lsp_types")
    assert(output.source.contains("inline std::string lsp_full_emit("))
    assert(output.source.contains("inline std::string lsp_emit_requests("))
    assert(output.source.contains("inline std::string lsp_emit_notifications("))
    assert(output.source.contains("inline int32_t main()"))

  test("full lspt-flavored generated files are checked in"):
    val files = List(
      "base.cos",
      "type_aliases.cos",
      "enums.cos",
      "structs.cos",
      "request.cos",
      "notification.cos",
    )

    files.foreach { name =>
      val path = s"packages/lsp-types/src/lsp/$name"
      val source = ParserFixtureManifest.readFile(path)

      assert(source.contains("Generated by packages/lsp-types Cosmo generator"))
      assert(source.contains("Flavor: lspt-style"))
    }

    val base = ParserFixtureManifest.readFile("packages/lsp-types/src/lsp/base.cos")
    val requests = ParserFixtureManifest.readFile("packages/lsp-types/src/lsp/request.cos")
    val notifications = ParserFixtureManifest.readFile("packages/lsp-types/src/lsp/notification.cos")
    val structs = ParserFixtureManifest.readFile("packages/lsp-types/src/lsp/structs.cos")

    assert(base.contains("type Uri = String"))
    assert(base.contains("type HashMap[K, V] = Map[K, V]"))
    assert(base.contains("class Union4[A, B, C, D]"))
    assert(structs.contains("class ReferenceParams"))
    assert(structs.contains("val TextDocument: TextDocumentIdentifier"))
    assert(structs.contains("val PartialResultToken: Option[ProgressToken]"))
    assert(structs.contains("class CodeActionClientCapabilitiesCodeActionLiteralSupportObject"))
    assert(requests.contains("class InitializeRequest {}"))
    assert(requests.contains("type InitializeRequestParams = InitializeParams"))
    assert(notifications.contains("class DidOpenTextDocumentNotification {}"))
    assert(notifications.contains("class PublishDiagnosticsNotification {}"))
